### ISSUE TITLE
Typo in tslib version makes installation impossible

### ISSUE THREAD

**Issue by Micky261** [codaline-io/angular-stl-model-viewer#594]
The double `^^` in front of the tslib version in [package.json](https://github.com/codaline-io/angular-stl-model-viewer/blob/master/projects/angular-stl-model-viewer/package.json#L24) breaks the installation process of this project's version 10.0.1.

```
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: tslib@^^2.6.2 isn't supported by any available resolver
    at vd.getResolverByDescriptor (<projectpath>\.yarn\releases\yarn-4.0.2.cjs:141:1698)       
    at vd.bindDescriptor (<projectpath>\.yarn\releases\yarn-4.0.2.cjs:141:1083)
    at St.preparePackage (<projectpath>\.yarn\releases\yarn-4.0.2.cjs:210:6173)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ne (<projectpath>\.yarn\releases\yarn-4.0.2.cjs:210:7583)
    at async Promise.allSettled (index 20)
    at async Uc (<projectpath>\.yarn\releases\yarn-4.0.2.cjs:140:53248)
➤ YN0000: └ Completed in 0s 358ms
➤ YN0000: · Failed with errors in 0s 373ms
```

Fixing this would be great! Thank you 😊

**Comment by KillerCodeMonkey** [comment]
try v10.0.2

**Comment by Micky261** [comment]
Both new versions 10.0.2 and 11.0.0 work now. Thanks!
